# Generated by Django 4.0.1 on 2022-01-25 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modele',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Marka', models.CharField(max_length=100)),
                ('Model', models.CharField(max_length=100)),
                ('Rok', models.IntegerField(max_length=7)),
                ('Przebieg', models.IntegerField(max_length=7)),
                ('Pojemnosc_Silnika', models.IntegerField(max_length=4)),
                ('Rodzaj_Paliwa', models.CharField(max_length=20)),
                ('Cena', models.DecimalField(decimal_places=2, max_digits=12)),
                ('Opis', models.TextField(blank=True)),
            ],
        ),
    ]
